version: '3'
services:
    web:
        container_name: nginx-newsletter
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - "../:/var/www/html"
            - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
        networks:
            newsletter-network:
                ipv4_address: 172.18.0.22
        environment:
          - TZ=Europe/Warsaw
        restart: always
    php:        
        container_name: php-newsletter
        build: ./php/
        volumes:
            - "../:/var/www/html"            
        networks:
            - newsletter-network
        environment:
          - TZ=Europe/Warsaw
        restart: always    
networks:
    newsletter-network:
        ipam:
            config:
                - subnet: 172.18.0.0/16
